Update weather_project.yml

diff --git a/.github/workflows/weather_project.yml b/.github/workflows/weather_project.yml
--- a/.github/workflows/weather_project.yml
+++ b/.github/workflows/weather_project.yml
@@ -6,9 +6,9 @@ on:
   workflow_dispatch:
      inputs: 
        log_error:
-       description: 'Generate log if tests fails'
-       required: true
-       default: 'true'
+         description: 'Generate log if tests fails'
+         required: true
+         default: 'true'
 
 env: 
   DOCKERFILE: ./Dockerfile
@@ -17,36 +17,38 @@ env:
 
 
 jobs:
-
   tests:
-  name: Running tests
-  runs-on: ubuntu-latest
-  if: ${{ github.events.input.log_error == 'true' }}
-  steps: 
+    name: Running tests
+    runs-on: ubuntu-latest
+    if: ${{ github.events.input.log_error == 'true' }}
+    steps: 
     - name: Checkout repo
       uses: actions/checkout@v4
 
     - name: Setting up Python 3.11
       uses: actions/setup-python@v5
       with: 
-        python-version: {{ env.PYTHON_VERSION }}  
+        python-version: ${{ env.PYTHON_VERSION }}  
 
     - name: Installing dependencies
       run: pip install -r requirements.txt
 
-    - name: Generate fail log 
-      if: ${{ env.TEST_FAILED == 'true' && github.event.inputs.log_error == 'true' }}
-      uses: action/upload-artifact@v4
-      with:
-         name: error-log 
-         path: test.log
+    - name: Run tests
+      run: | 
+        pytest || echo "TEST_FAILED=true" >> $GITHUB_ENV
 
+    - name: Generate log if failure
+      if: ${{ env.TEST_FAILED == 'true' && github.event.inputs.log_error == 'true' }}
+      uses: actions/upload-artifact@v4
+      with: 
+        name: error-log
+        path: test.log
 
   build-and-push:
     name: Building and pushing Docker image        
     runs-on: ubuntu-latest
     needs: tests
-    if: ${{ needs.tests.results == 'success' }}
+    if: ${{ needs.tests.result == 'success' }}
     steps:
       - name: Check out code
         uses: actions/checkout@v4
@@ -67,5 +69,5 @@ jobs:
           file: ${{ env.DOCKERFILE }}
           push: true 
           tags: |
-            {{ env.IMAGE_NAME }}:latest
-             {{ env.IMAGE_NAME }}:1.0
+            ${{ env.IMAGE_NAME }}:latest
+             ${{ env.IMAGE_NAME }}:1.0
